### ISSUE TITLE
Data visualization for Question #4

### ISSUE THREAD

**Issue by madireyn** [ARMANAZHAND/info_201_project#8]
How has crime rate changed over the past 5 years?

**Comment by ARMANAZHAND** [comment]
Possibly line chart with crime selection or the colour coded blocks

**Comment by madireyn** [comment]
Will either be doing some sort of tree map to visualize volume of crimes in each year + prevalent crimes, or a line graph
https://stackoverflow.com/questions/51079047/how-to-plot-treemap-choropleth-in-r-for-shiny-app
